# paths to ignore during linting. Takes precedence over `included`
excluded:
  - Carthage
  - Pods
  - Sources/Generated/

included:
  - Modules
  - Sources

# Disabled rules
disabled_rules:
- number_separator
- trailing_comma
- implicitly_unwrapped_optional
- discouraged_optional_collection
- discouraged_optional_boolean

# Enabled non-default rules
opt_in_rules:
 - todo
 - unused_optional_binding
 - array_init
 - anyobject_protocol
 - closure_spacing
 - closure_end_indentation
 - contains_over_first_not_nil
 - collection_alignment
 - convenience_type
 - discouraged_object_literal
 - empty_count
 - empty_string
 - empty_xctest_method
 - explicit_init
 - extension_access_modifier
 - first_where
 - force_unwrapping
 - implicitly_unwrapped_optional
 - identical_operands
 - joined_default_parameter
 - let_var_whitespace
 - last_where
 - literal_expression_end_indentation
 - legacy_multiple
 - legacy_random
 - lower_acl_than_parent
 - multiline_parameters_brackets
 - multiline_function_chains
 - multiline_arguments
 - multiple_closures_with_trailing_closure
 - modifier_order
 - nimble_operator
 - number_separator
 - operator_usage_whitespace
 - overridden_super_call
 - override_in_extension
 - private_action
 - private_outlet
 - prohibited_super_call
 - pattern_matching_keywords
 - redundant_nil_coalescing
 - sorted_first_last
 - fallthrough
 - fatal_error_message
 - quick_discouraged_call
 - redundant_type_annotation
 - required_enum_case
 - reduce_into
 - single_test_class
 - strict_fileprivate
 - static_operator
 - toggle_bool
 - unneeded_parentheses_in_closure_argument
 - unowned_variable_capture
 - unused_import
 - untyped_error_in_catch
 - vertical_whitespace_closing_braces
 - xct_specific_matcher
 - yoda_condition
 - closure_body_length
 - multiline_parameters
 - file_name
 - object_literal
 - vertical_parameter_alignment_on_call
 - attributes
 - switch_case_on_newline

# Rules customization
line_length:
 warning: 120
 error: 200
 ignores_comments: true
 ignores_urls: true

function_body_length:
 warning: 70
 error: 100

vertical_parameter_alignment:
  severity: error

vertical_parameter_alignment_on_call:
  severity: error
  
anyobject_protocol:
  severity: error

array_init:
  severity: error

attributes:
  severity: error
  always_on_same_line: ["@NSCopying", "@NSManaged", "@IBAction", "@IBOutlet", "@IBInspectable", "@inlinable", "@usableFromInline"]
  always_on_line_above: ["@IBDesignable", "@available", "@convention", "@discardableResult", "@dynamicMemberLookup", "@objcMembers", "@nonobjc", "@objc"]

block_based_kvo:
  severity: error

class_delegate_protocol:
  severity: error

closing_brace:
  severity: error

closure_end_indentation:
  severity: error

closure_parameter_position:
  severity: error

closure_spacing:
  severity: error

colon:
  severity: error

comma:
  severity: error

contains_over_first_not_nil:
  severity: error

convenience_type:
  severity: error

cyclomatic_complexity:
  warning: 7
  error: 15
  ignores_case_statements: true

discouraged_direct_init:
  severity: error

discouraged_object_literal:
  severity: error

empty_count:
  severity: error

empty_enum_arguments:
  severity: error

empty_parameters:
  severity: error

empty_parentheses_with_trailing_closure:
  severity: error

empty_string:
  severity: error

explicit_init:
  severity: error

fatal_error_message:
  severity: error

file_length:
  warning: 750
  ignore_comment_only_lines: true

file_name:
  severity: error

first_where:
  severity: error

for_where:
  severity: error

function_body_length:
  warning: 60
  error: 200

function_parameter_count:
  warning: 4
  error: 6

identifier_name:
  min_length:
    error: 0
    warning: 1
  max_length:
    error: 64
    warning: 48

is_disjoint:
  severity: error

large_tuple:
  warning: 3
  error: 4

legacy_cggeometry_functions:
  severity: error

legacy_constructor:
  severity: error

line_length:
  warning: 165
  error: 320
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

literal_expression_end_indentation:
  severity: error

lower_acl_than_parent:
  severity: warning

mark:
  severity: error

modifier_order:
  severity: error
  preferred_modifier_order: ["acl", "setterACL", "override", "mutators", "final", "dynamic", "typeMethods", "convenience", "required", "lazy", "owned"]

multiple_closures_with_trailing_closure:
  severity: error

multiline_function_chains:
  severity: error

multiline_parameters:
  severity: error
  first_argument_location: next_line

nesting:
  type_level: 3
  function_level: 5

notification_center_detachment:
  severity: error

object_literal:
  severity: error
  color_literal: false

opening_brace:
  severity: error

operator_usage_whitespace:
  severity: error

operator_whitespace:
  severity: error

override_in_extension:
  severity: error

overridden_super_call:
  severity: error

pattern_matching_keywords:
  severity: error

prohibited_super_call:
  severity: error

private_action:
  severity: error

private_outlet:
  severity: error

protocol_property_accessors_order:
  severity: error

redundant_discardable_let:
  severity: error

redundant_nil_coalescing:
  severity: error

redundant_type_annotation:
  severity: error

redundant_void_return:
  severity: error

return_arrow_whitespace:
  severity: error

shorthand_operator:
  severity: error

sorted_first_last:
  severity: error

statement_position:
  severity: error

switch_case_alignment:
  severity: error

switch_case_on_newline:
  severity: error

syntactic_sugar:
  severity: error

trailing_whitespace:
  ignores_empty_lines: true
  severity: error

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 64

type_body_length:
  warning: 350
  error: 500

unneeded_break_in_switch:
  severity: error

unneeded_parentheses_in_closure_argument:
  severity: error

untyped_error_in_catch:
  severity: error

unused_closure_parameter:
  severity: error

unused_enumerated:
  severity: error

unused_optional_binding:
  severity: error

multiline_parameters_brackets:
  severity: error

unused_capture_list:
  severity: error

vertical_whitespace_closing_braces:
  severity: error

trailing_newline:
  severity: error
  
lower_acl_than_parent:
  severity: error

void_return:
  severity: error

vertical_whitespace:
  severity: error

closure_body_length:
  warning: 30
  error: 100
  
custom_rules:
  fixme_error:
    included: ".*\\.swift"
    name: "FIXME Error"
    regex: "(FIXME:)"
    capture_group: 0
    match_kinds:
      - comment
    message: "FIXMEs should be resolved before release"
    severity: error
